/*
 * Star.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import code.name;
import code.song;
import code.star;

import sql.DataConnect;

/**
 *
 * @author  __USER__
 */
public class Star extends javax.swing.JFrame {

	/** Creates new form Star */
	public Star() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jButton1.setText("\u5237\u65b0");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u8fd4\u56de");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setText("\u6211\u7684\u6536\u85cf");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(
						jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE,
						370, Short.MAX_VALUE).addContainerGap()).addGroup(
				layout.createSequentialGroup().addGap(69, 69, 69).addComponent(
						jButton1).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						132, Short.MAX_VALUE).addComponent(jButton2).addGap(73,
						73, 73)).addGroup(
				layout.createSequentialGroup().addGap(144, 144, 144)
						.addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 110,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(146, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												45,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												243,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton2))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		dispose();
		new ruser().setVisible(true);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		ArrayList<name> i = new ArrayList<name>();
		String url = "select * from temporary1";
		try {
			ResultSet rs = DataConnect.getStat().executeQuery(url);
			while (rs.next()) {
				i.add(new name(rs.getString("name")));
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			System.out.println("error");
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		String name = i.get(0).getName();
		
		ArrayList a = new ArrayList();
		String url1 = "select * from star where username ="+name+";";
		try {
			ResultSet rs = DataConnect.getStat().executeQuery(url1);
			while (rs.next()) {
				a.add(rs.getString("songname"));
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			System.out.println("error");
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		ArrayList<song> s = new  ArrayList<song>();
		for(int i1 = 0; i1<a.size(); i1++){
			System.out.println(a.get(i1));
			String q =(String) a.get(i1);
			String url11 = "select * from song where id ="+q+";";
			try {
				ResultSet rs = DataConnect.getStat().executeQuery(url11);
				while (rs.next()) {
					s.add(new song(rs.getString("name"),rs.getString("time")
							,rs.getString("Author"),rs.getString("id")));
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				System.out.println("error");
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		}
		
		for(int i2 = 0; i2<s.size();i2++){
			System.out.println(s.get(i2).getName());
			jTextArea1.append("id:"+((song) s.get(i2)).getId()+
					"   name:"+((song) s.get(i2)).getName()+	
					"   Author:"+((song) s.get(i2)).getAuthor()+
					"   time:"+((song) s.get(i2)).getTime()+"\n");
		}
	}

	/**
	 * @param args the command line arguments
	 */
	

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables

}